import { FormEvent, useEffect, useState } from "react";
import { api } from "./services/api";

type User={id:string;name:string;email:string;role:"ADMIN"|"STAFF";isActive?:boolean};
type Customer={_id:string;customerId:string;name:string;mobile:string;email?:string;city?:string;occupation?:string};
type Loan={_id:string;loanId:string;customerId:Customer;loanType:string;requiredAmount:number;approvedAmount?:number;financeCompany?:string;status:string;commission:number;applicationDate?:string;expectedDisbursementDate?:string;disbursementDate?:string;rejectionReason?:string;notes?:string};
type Car={_id:string;vehicleId:string;registrationNumber:string;make:string;model:string;year:number;ownerNumber:number;km:number;fuel:string;purchasePrice:number;expenseTotal?:number;totalInvestment?:number;status:string;sellerId?:Customer};
type Dashboard={customers:number;activeLoans:number;carsInInventory:number;carsSold:number;totalSales:number;totalInvestment:number;totalProfit:number};

const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v);
const nav=[["Dashboard","Dashboard"],["Loan Dashboard","Loans"],["Applications","Loans"],["Active Loans","Loans"],["Car Buying","Car Buying"],["Car Inventory","Cars"],["Car Sold","Sold"],["Expenses","Expenses"],["Customers","Customers"],["Customer History","Customers"],["Car Profit","Profit"],["Loan Revenue","Loans"],["Reports","Dashboard"]];

export default function App(){
 const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{api.get("/auth/me").then(r=>setUser(r.data.data)).catch(()=>localStorage.removeItem("sm_token")).finally(()=>setLoading(false))},[]);
 if(loading)return <div className="center-page"><div className="loader-card">Loading SM Associate...</div></div>;
 if(!user)return <Login onLogin={setUser}/>;
 return <ManagementApp user={user} onLogout={()=>{localStorage.removeItem("sm_token");setUser(null)}}/>;
}

function PremiumSelect({value,onChange,placeholder,options}:{value:string;onChange:(value:string)=>void;placeholder:string;options:{value:string;label:string}[]}){
 const[open,setOpen]=useState(false);const[search,setSearch]=useState("");
 const selected=options.find(x=>x.value===value);const filtered=options.filter(x=>x.label.toLowerCase().includes(search.toLowerCase()));
 useEffect(()=>{
  if(!open)return;
  const closeOther=()=>{setOpen(false);setSearch("")};
  window.addEventListener("premium-select-open",closeOther);
  const handleOutside=(e:MouseEvent)=>{const target=e.target as Node;if(!(target as Element)?.closest?.(".premium-select")){setOpen(false);setSearch("")}};
  document.addEventListener("mousedown",handleOutside);
  return()=>{window.removeEventListener("premium-select-open",closeOther);document.removeEventListener("mousedown",handleOutside)};
 },[open]);
 function toggle(){if(!open){window.dispatchEvent(new Event("premium-select-open"));setOpen(true)}else setOpen(false);setSearch("")}
 return <div className="premium-select">
  <button type="button" className={open?"premium-select-trigger open":"premium-select-trigger"} onClick={toggle} aria-expanded={open}><span className={selected?"selected":"placeholder"}>{selected?.label||placeholder}</span><span className="premium-select-chevron" aria-hidden="true"></span></button>
  {open&&<div className="premium-select-menu"><input autoFocus className="premium-select-search" placeholder="Search..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="premium-select-options">{!filtered.length?<div className="premium-select-empty">No matching results</div>:filtered.map(x=><button type="button" key={x.value} className={x.value===value?"premium-select-option active":"premium-select-option"} onClick={()=>{onChange(x.value);setOpen(false);setSearch("")}}><span>{x.label}</span>{x.value===value&&<span className="premium-select-check">✓</span>}</button>)}</div></div>}
 </div>
}

function PremiumLogo({compact=false}:{compact?:boolean}){return <img className={compact?"brand-logo-image compact":"brand-logo-image"} src="/assets/sm-associate-logo.png" alt="SM Associate" />}

function TopBar({user}:{user:User}){const[q,setQ]=useState("");function submit(e:FormEvent){e.preventDefault();const term=q.trim();if(term)window.dispatchEvent(new CustomEvent("sm-global-search",{detail:{query:term}}))}return <div className="topbar"><div className="topbar-search"><form onSubmit={submit}><span className="search-icon" aria-hidden="true"></span><input aria-label="Search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers, loans, vehicles..." /></form></div><div className="topbar-actions"><button type="button" className="topbar-icon" aria-label="Notifications"><span className="bell-icon"></span></button><div className="topbar-profile"><span className="profile-avatar">{user.name.trim().slice(0,1).toUpperCase()||"S"}</span><span className="profile-copy"><strong>{user.name}</strong><small>{user.role}</small></span><span className="profile-chevron"></span></div></div></div>}

function Login({onLogin}:{onLogin:(u:User)=>void}){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const r=await api.post("/auth/login",{email,password});localStorage.setItem("sm_token",r.data.data.token);onLogin(r.data.data.user)}catch(e:any){setError(e?.response?.data?.message||"Unable to sign in. Please try again.")}finally{setBusy(false)}}
 return <div className="login-page"><div className="login-panel"><PremiumLogo /><h1>Management System</h1><p>Secure access for finance and car operations.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error-box">{error}</div>}<button className="primary-btn" disabled={busy}>{busy?"Signing in...":"Sign in"}</button></form></div></div>
}

function navigateTo(page:string,context?:any){window.dispatchEvent(new CustomEvent("sm-navigate",{detail:{page,context}}))}
function ManagementApp({user,onLogout}:{user:User;onLogout:()=>void}){
 const[page,setPage]=useState("Dashboard");const[context,setContext]=useState<any>(null);
 useEffect(()=>{const handler=(e:Event)=>{const d=(e as CustomEvent).detail||{};setContext(d.context??null);if(d.page)setPage(d.page)};window.addEventListener("sm-navigate",handler);return()=>window.removeEventListener("sm-navigate",handler)},[]);
 const groups=[
  {title:"GENERAL",items:["Dashboard"]},
  {title:"LOAN MANAGEMENT",items:["Loan Dashboard","Applications","Active Loans","Follow-ups"]},
  {title:"CAR MANAGEMENT",items:user.role==="ADMIN"?["Car Buying","Car Inventory","Car Sold","Expenses"]:["Car Buying","Car Inventory"]},
  {title:"CUSTOMER MANAGEMENT",items:["Customers","Customer History"]},
  {title:"PROFIT & REPORTS",items:user.role==="ADMIN"?["Car Profit","Loan Revenue","Reports"]:["Reports"]},
  ...(user.role==="ADMIN"?[{title:"ADMINISTRATION",items:["Users"]}]:[])
 ];
 const activeGroup=groups.findIndex(g=>g.items.includes(page));
 const[openGroup,setOpenGroup]=useState(activeGroup);
 useEffect(()=>{setOpenGroup(activeGroup)},[activeGroup]);
 return <div className="app"><aside className="sidebar"><div className="brand"><PremiumLogo compact /></div><nav>{groups.map((group,index)=><SidebarGroup key={group.title} title={group.title} items={group.items} open={openGroup===index} onToggle={()=>setOpenGroup(openGroup===index?-1:index)} page={page} setPage={setPage}/>)}</nav>
 <div className="sidebar-user"><strong>{user.name}</strong><span>{user.role}</span><button onClick={onLogout}>Sign out</button></div></aside>
 <main className="main"><TopBar user={user}/><header><div><span className="eyebrow">SM ASSOCIATE / MANAGEMENT</span><h1>{page}</h1><p>Manage finance, customers and automotive operations.</p></div></header><PageContent page={page} userRole={user.role} context={context}/></main></div>
}
function SidebarGroup({title,items,open,onToggle,page,setPage}:{title:string;items:string[];open:boolean;onToggle:()=>void;page:string;setPage:(x:string)=>void}){
 return <section className={open?"sidebar-group open":"sidebar-group"}><button type="button" className="sidebar-group-trigger" onClick={onToggle} aria-expanded={open}><span>{title}</span><span className="sidebar-group-chevron" aria-hidden="true"></span></button>{open&&<div className="sidebar-group-menu">{items.map(item=><Nav key={item} label={item} page={page} setPage={setPage}/>)}</div>}</section>
}
function Nav({label,page,setPage}:{label:string;page:string;setPage:(x:string)=>void}){return <button className={page===label?"nav-link active":"nav-link"} onClick={()=>setPage(label)}>{label}</button>}

function PageContent({page,userRole,context}:{page:string;userRole:"ADMIN"|"STAFF";context?:any}){
 if(page==="Create User")return <CreateUserPage/>;
 if(page==="Add Customer")return <AddCustomerPage/>;
 if(page==="New Loan")return <NewLoanPage/>;
 if(page==="Add Expense"||page==="Edit Expense")return <ExpenseFormPage expenseId={context?.expenseId} />;
 if(page==="Users")return <UsersPage/>;
 if(page==="Customers"||page==="Customer History")return <CustomersPage historyOnly={page==="Customer History"}/>;
 if(page==="Loans"||page==="Loan Dashboard"||page==="Applications"||page==="Active Loans"||page==="Follow-ups"||page==="Loan Revenue")return <LoansPage filter={page}/>;
 if(page==="Cars"||page==="Car Inventory")return <CarsPage mode={page} userRole={userRole}/>;
 if(page==="Expenses")return <ExpensesPage/>;
 if(page==="Car Profit")return <ProfitPage/>;
 if(page==="Car Buying")return <CarBuyingPage/>;
 if(page==="Car Sold")return <CarSoldPage/>;
 return <DashboardPage/>;
}

function UsersPage(){
 const[users,setUsers]=useState<User[]>([]);const[selected,setSelected]=useState<User|null>(null);const[message,setMessage]=useState("");const[error,setError]=useState("");
 const load=()=>api.get("/auth/users").then(r=>setUsers(r.data.data)).catch(e=>setError(e?.response?.data?.message||"Unable to load users."));useEffect(()=>{load()},[]);
 async function toggle(u:User){setMessage("");setError("");try{await api.patch("/auth/users/"+u.id,{isActive:!u.isActive});setMessage("User access updated.");load()}catch(e:any){setError(e?.response?.data?.message||"Unable to update user.")}}
 async function changeRole(u:User,role:"ADMIN"|"STAFF"){setMessage("");setError("");try{await api.patch("/auth/users/"+u.id,{role});setMessage("Role updated.");load()}catch(e:any){setError(e?.response?.data?.message||"Unable to update role.")}}
 async function remove(u:User){if(!window.confirm("Delete this user permanently?"))return;setMessage("");setError("");try{await api.delete("/auth/users/"+u.id);setMessage("User deleted successfully.");load();if(selected?.id===u.id)setSelected(null)}catch(e:any){setError(e?.response?.data?.message||"Unable to delete user.")}}
 return <section className="panel"><div className="panel-head"><div><h2>User Management</h2><p>Manage staff accounts and roles.</p></div><button className="primary-btn" onClick={()=>navigateTo("Create User")}>Create User</button></div>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td><PremiumSelect value={u.role} onChange={value=>changeRole(u,value as "ADMIN"|"STAFF")} placeholder="Select role" options={[{value:"STAFF",label:"STAFF"},{value:"ADMIN",label:"ADMIN"}]}/></td><td><span className="status">{u.isActive?"ACTIVE":"INACTIVE"}</span></td><td><div className="action-buttons"><button className="small-btn" onClick={()=>setSelected(u)}>View</button><button className="small-btn delete-btn" onClick={()=>remove(u)}>Delete</button><button className="small-btn" onClick={()=>toggle(u)}>{u.isActive?"Deactivate":"Activate"}</button></div></td></tr>)}</tbody></table></div></section>{selected&&<UserViewModal user={selected} onClose={()=>setSelected(null)}/>}
}
function UserViewModal({user,onClose}:{user:User;onClose:()=>void}){return <div className="modal-backdrop"><section className="modal-panel narrow"><div className="panel-head"><div><h2>{user.name}</h2><p>User account details.</p></div><button className="small-btn" onClick={onClose}>Close</button></div><div className="detail-grid"><div><b>Name</b><span>{user.name}</span></div><div><b>Email</b><span>{user.email}</span></div><div><b>Role</b><span>{user.role}</span></div><div><b>Status</b><span>{user.isActive?"ACTIVE":"INACTIVE"}</span></div></div></section></div>}

function ExpenseViewModal({expense,onClose}:{expense:CarExpense;onClose:()=>void}){return <div className="modal-backdrop"><section className="modal-panel narrow"><div className="panel-head"><div><h2>Expense Details</h2><p>{expense.carId?.vehicleId||"Vehicle expense"}</p></div><button className="small-btn" onClick={onClose}>Close</button></div><div className="detail-grid"><div><b>Vehicle</b><span>{expense.carId?.vehicleId||"—"}</span></div><div><b>Registration</b><span>{expense.carId?.registrationNumber||"—"}</span></div><div><b>Category</b><span>{expense.category}</span></div><div><b>Amount</b><span>{money(expense.amount)}</span></div></div><div className="metric-row"><span>Description</span><strong>{expense.description||"—"}</strong></div><div className="metric-row"><span>Date</span><strong>{expense.date?new Date(expense.date).toLocaleDateString("en-IN"):"—"}</strong></div></section></div>}

function CarFinancialModal({state,onClose}:{state:any;onClose:()=>void}){const d=state.details;const car=state.car;return <div className="modal-backdrop"><section className="modal-panel"><div className="panel-head"><div><h2>{car.vehicleId} · {car.make} {car.model}</h2><p>Vehicle financial details.</p></div><button className="small-btn" onClick={onClose}>Close</button></div>{state.loading?<div className="loader-card">Loading vehicle details...</div>:<><div className="detail-grid"><div><b>Registration</b><span>{car.registrationNumber}</span></div><div><b>Purchase Price</b><span>{money(car.purchasePrice)}</span></div><div><b>Expenses</b><span>{money(d?.expenseTotal??0)}</span></div><div><b>Total Investment</b><span>{money(d?.totalInvestment??car.purchasePrice)}</span></div><div><b>Status</b><span className="status">{car.status}</span></div><div><b>KM</b><span>{car.km?.toLocaleString("en-IN")}</span></div></div>{d?.sale&&<div className="modal-section"><h3>Sale</h3><div className="detail-grid"><div><b>Selling Price</b><span>{money(d.sale.sellingPrice)}</span></div><div><b>Selling Expenses</b><span>{money(d.sale.sellingExpenses)}</span></div><div><b>Net Profit</b><span className={d.sale.profit>=0?"profit-positive":"profit-negative"}>{money(d.sale.profit)}</span></div></div></div>}</>}</section></div>}

function BackButton({page}:{page:string}){return <button type="button" className="small-btn" onClick={()=>navigateTo(page)}>← Back</button>}

function CreateUserPage(){
 const[form,setForm]=useState({name:"",email:"",password:"",role:"STAFF"});const[message,setMessage]=useState("");const[error,setError]=useState("");
 async function add(e:FormEvent){e.preventDefault();setMessage("");setError("");try{await api.post("/auth/users",form);setMessage("User created successfully.");setForm({name:"",email:"",password:"",role:"STAFF"})}catch(e:any){setError(e?.response?.data?.message||"Unable to create user.")}}
 return <section className="panel narrow"><div className="panel-head"><div><p>Create a new staff or admin account.</p></div><BackButton page="Users"/></div>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<form onSubmit={add}><input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Password (min 8 characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength={8} required/><PremiumSelect value={form.role} onChange={value=>setForm({...form,role:value})} placeholder="Select role" options={[{value:"STAFF",label:"STAFF"},{value:"ADMIN",label:"ADMIN"}]}/><button className="primary-btn">Create User</button></form></section>
}

function AddCustomerPage(){
 const[form,setForm]=useState({name:"",mobile:"",email:"",city:"",occupation:""});const[message,setMessage]=useState("");const[error,setError]=useState("");
 async function add(e:FormEvent){e.preventDefault();setMessage("");setError("");try{await api.post("/customers",form);setMessage("Customer added successfully.");setForm({name:"",mobile:"",email:"",city:"",occupation:""})}catch(e:any){setError(e?.response?.data?.message||"Unable to save customer.")}}
 return <section className="panel narrow"><div className="panel-head"><div><p>Customer ID will be generated automatically.</p></div><BackButton page="Customers"/></div>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<form onSubmit={add}>{["name","mobile","email","city","occupation"].map(k=><input key={k} placeholder={k[0].toUpperCase()+k.slice(1)} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==="name"||k==="mobile"}/>)}<button className="primary-btn">Save Customer</button></form></section>
}

function NewLoanPage(){
 const[customers,setCustomers]=useState<Customer[]>([]);const[customerMode,setCustomerMode]=useState<"EXISTING"|"NEW">("EXISTING");const[newCustomer,setNewCustomer]=useState({name:"",mobile:"",email:"",city:"",occupation:""});const[form,setForm]=useState({customerId:"",loanType:"Home Loan",requiredAmount:"",financeCompany:"",commission:"",notes:""});const[message,setMessage]=useState("");const[error,setError]=useState("");
 useEffect(()=>{api.get("/customers").then(r=>setCustomers(r.data.data)).catch(()=>{})},[]);
 async function add(e:FormEvent){e.preventDefault();setMessage("");setError("");try{let customerId=form.customerId;if(customerMode==="NEW"){const customer=await api.post("/customers",newCustomer);customerId=customer.data.data._id}if(!customerId)throw new Error("Select an existing customer or enter a new customer.");await api.post("/loans",{...form,customerId,requiredAmount:Number(form.requiredAmount),commission:Number(form.commission||0)});setMessage("Loan application created successfully.");setForm({customerId:"",loanType:"Home Loan",requiredAmount:"",financeCompany:"",commission:"",notes:""});setNewCustomer({name:"",mobile:"",email:"",city:"",occupation:""});setCustomerMode("EXISTING")}catch(e:any){setError(e?.response?.data?.message||e?.message||"Unable to create loan.")}}
 return <section className="panel narrow"><div className="panel-head"><div><p>New applications start with status <strong>ENTERED</strong>.</p></div><BackButton page="Applications"/></div>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<form onSubmit={add}><PremiumSelect value={customerMode} onChange={value=>{const mode=value as "EXISTING"|"NEW";setCustomerMode(mode);setForm({...form,customerId:""})}} placeholder="Select customer type" options={[{value:"EXISTING",label:"Existing Customer"},{value:"NEW",label:"New Customer"}]}/>{customerMode==="EXISTING"?<PremiumSelect value={form.customerId} onChange={value=>setForm({...form,customerId:value})} placeholder="Select existing customer" options={customers.map(c=>({value:c._id,label:c.customerId+" — "+c.name+" — "+c.mobile}))}/>:<div className="form-grid"><input placeholder="Customer name" value={newCustomer.name} onChange={e=>setNewCustomer({...newCustomer,name:e.target.value})} required/><input placeholder="Mobile number" value={newCustomer.mobile} onChange={e=>setNewCustomer({...newCustomer,mobile:e.target.value})} required/><input type="email" placeholder="Email" value={newCustomer.email} onChange={e=>setNewCustomer({...newCustomer,email:e.target.value})}/><input placeholder="City" value={newCustomer.city} onChange={e=>setNewCustomer({...newCustomer,city:e.target.value})}/><input placeholder="Occupation" value={newCustomer.occupation} onChange={e=>setNewCustomer({...newCustomer,occupation:e.target.value})}/></div>}<PremiumSelect value={form.loanType} onChange={value=>setForm({...form,loanType:value})} placeholder="Select loan type" options={["Home Loan","Car Loan","Business Loan","Personal Loan"].map(x=>({value:x,label:x}))}/><input type="number" placeholder="Required amount" value={form.requiredAmount} onChange={e=>setForm({...form,requiredAmount:e.target.value})} required/><input placeholder="Finance company" value={form.financeCompany} onChange={e=>setForm({...form,financeCompany:e.target.value})}/><input type="number" placeholder="Commission" value={form.commission} onChange={e=>setForm({...form,commission:e.target.value})}/><textarea placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="primary-btn">Create Application</button></form></section>
}

function ExpenseFormPage({expenseId}:{expenseId?:string}){
 const[cars,setCars]=useState<Car[]>([]);const[form,setForm]=useState({carId:"",category:"Service",amount:"",description:"",date:new Date().toISOString().slice(0,10)});const[message,setMessage]=useState("");const[error,setError]=useState("");
 const editing=Boolean(expenseId);
 useEffect(()=>{api.get("/cars",{params:{status:"AVAILABLE"}}).then(r=>setCars(r.data.data)).catch(()=>{});if(expenseId){api.get("/cars/expenses").then(r=>{const x=(r.data.data||[]).find((e:any)=>e._id===expenseId);if(x)setForm({carId:x.carId?._id||x.carId||"",category:x.category,amount:String(x.amount),description:x.description||"",date:x.date?new Date(x.date).toISOString().slice(0,10):new Date().toISOString().slice(0,10)})}).catch(()=>{})}},[expenseId]);
 async function save(e:FormEvent){e.preventDefault();setMessage("");setError("");try{if(editing){const carId=form.carId;await api.patch("/cars/"+carId+"/expenses/"+expenseId,{category:form.category,amount:Number(form.amount),description:form.description,date:form.date});setMessage("Expense updated successfully.")}else{if(!form.carId)throw new Error("Select a vehicle.");await api.post("/cars/"+form.carId+"/expenses",{category:form.category,amount:Number(form.amount),description:form.description,date:form.date});setMessage("Expense added successfully.");setForm({carId:"",category:"Service",amount:"",description:"",date:new Date().toISOString().slice(0,10)})}}catch(e:any){setError(e?.response?.data?.message||e?.message||"Unable to save expense.")}}
 return <section className="panel narrow"><div className="panel-head"><div><p>{editing?"Update the selected expense.":"Add an expense to the vehicle's total investment."}</p></div><BackButton page="Expenses"/></div>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<form onSubmit={save}>{!editing&&<PremiumSelect value={form.carId} onChange={value=>setForm({...form,carId:value})} placeholder="Select vehicle" options={cars.map(c=>({value:c._id,label:c.vehicleId+" — "+c.registrationNumber+" — "+c.make+" "+c.model}))}/>}<PremiumSelect value={form.category} onChange={value=>setForm({...form,category:value})} placeholder="Select category" options={["Service","Repair","Tyres","Insurance","Cleaning","Accessories","RC / Documents","Other"].map(x=>({value:x,label:x}))}/><input type="number" min="0" step="0.01" placeholder="Expense amount" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="primary-btn">{editing?"Update Expense":"Add Expense"}</button></form></section>
}

function DashboardPage(){
 const[data,setData]=useState<any>(null);const[error,setError]=useState("");
 useEffect(()=>{api.get("/reports/dashboard").then(r=>setData(r.data.data)).catch(e=>setError(e?.response?.data?.message||"Unable to load dashboard."))},[]);
 const pipeline=data?.loanPipeline||{};
 return <>{error&&<div className="error-box">{error}</div>}<section className="cards"><Card label="Total Customers" value={String(data?.customers??0)}/><Card label="Active Loans" value={String(data?.activeLoans??0)}/><Card label="Cars in Inventory" value={String(data?.carsInInventory??0)}/><Card label="Cars Sold" value={String(data?.carsSold??0)}/><Card label="Open Follow-ups" value={String(data?.openFollowUps??0)}/><Card label="Inventory Value" value={money(data?.inventoryValue??0)}/></section><section className="profit-card"><div><span>Total Investment</span><strong>{money(data?.totalInvestment??0)}</strong></div><div><span>Total Sales</span><strong>{money(data?.totalSales??0)}</strong></div><div><span>Net Car Profit</span><strong>{money(data?.totalProfit??0)}</strong></div></section><section className="panel"><div className="panel-head"><div><h2>Loan Pipeline</h2><p>Current application distribution by status.</p></div></div><div className="pipeline">{["ENTERED","DOCUMENTS_PENDING","SUBMITTED","UNDER_REVIEW","APPROVED","REJECTED","DISBURSED","CLOSED"].map(s=><div className="pipeline-item" key={s}><span>{s.replaceAll("_"," ")}</span><strong>{pipeline[s]||0}</strong></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>This Month</h2><p>Current-month operating performance.</p></div></div><div className="cards compact"><Card label="Car Sales" value={money(data?.monthly?.carSales?.sales??0)}/><Card label="Car Profit" value={money(data?.monthly?.carSales?.profit??0)}/><Card label="Loan Applications" value={String(data?.monthly?.loans?.count??0)}/><Card label="Loan Commission" value={money(data?.monthly?.loans?.commission??0)}/></div></section></>;
}
function Card({label,value}:{label:string;value:string}){return <div className="card"><span>{label}</span><strong>{value}</strong></div>}

function CustomersPage({historyOnly}:{historyOnly:boolean}){
 const[customers,setCustomers]=useState<Customer[]>([]);const[search,setSearch]=useState("");const[selected,setSelected]=useState<Customer|null>(null);const[history,setHistory]=useState<any>(null);const[message,setMessage]=useState("");
 const load=()=>api.get("/customers",{params:{search}}).then(r=>setCustomers(r.data.data)).catch(()=>setMessage("Unable to load customers."));useEffect(()=>{load()},[search]);
 async function open(c:Customer){setSelected(c);try{const r=await api.get("/customers/"+c._id+"/history");setHistory(r.data.data)}catch(e:any){setMessage(e?.response?.data?.message||"Unable to load customer history.")}}
 async function remove(c:Customer){if(!window.confirm("Delete this customer permanently?"))return;setMessage("");try{await api.delete("/customers/"+c._id);setMessage("Customer deleted successfully.");load();if(selected?._id===c._id){setSelected(null);setHistory(null)}}catch(e:any){setMessage(e?.response?.data?.message||"Unable to delete customer.")}}
 return <><section className="panel"><div className="panel-head"><div><p>{historyOnly?"Select a customer to view their complete transaction history.":"Manage customer records and linked transactions."}</p></div>{!historyOnly&&<button className="primary-btn" onClick={()=>navigateTo("Add Customer")}>Add Customer</button>}</div><input className="search" placeholder="Search name, mobile or customer ID..." value={search} onChange={e=>setSearch(e.target.value)}/>{message&&<div className="success-box">{message}</div>}<div className="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Mobile</th><th>City</th><th>Occupation</th><th>Action</th></tr></thead><tbody>{customers.map(c=><tr key={c._id}><td>{c.customerId}</td><td>{c.name}</td><td>{c.mobile}</td><td>{c.city||"—"}</td><td>{c.occupation||"—"}</td><td><div className="action-buttons"><button className="small-btn" onClick={()=>open(c)}>View</button><button className="small-btn delete-btn" onClick={()=>remove(c)}>Delete</button></div></td></tr>)}{!customers.length&&<tr><td colSpan={6} className="empty">No customers found.</td></tr>}</tbody></table></div></section>{selected&&<CustomerHistoryModal customer={selected} data={history} onClose={()=>{setSelected(null);setHistory(null)}}/>}</>
}
function CustomerHistoryModal({customer,data,onClose}:{customer:Customer;data:any;onClose:()=>void}){
 const s=data?.summary;
 return <div className="modal-backdrop"><section className="modal-panel customer-history-modal"><div className="panel-head"><div><h2>{customer.customerId} · {customer.name}</h2><p>{customer.mobile}{customer.city?" · "+customer.city:""}{customer.occupation?" · "+customer.occupation:""}</p></div><button className="small-btn" onClick={onClose}>Close</button></div>{!data?<div className="loader-card">Loading customer history...</div>:<><div className="cards compact"><Card label="Loans" value={String(s?.loanCount??0)}/><Card label="Approved Amount" value={money(s?.loanApprovedAmount??0)}/><Card label="Loan Commission" value={money(s?.loanCommission??0)}/><Card label="Cars Bought" value={String(s?.carsBoughtCount??0)}/><Card label="Cars Sold" value={String(s?.carsSoldCount??0)}/><Card label="Cars Bought Value" value={money(s?.carsBoughtValue??0)}/></div><HistorySection title="Loans"><table><thead><tr><th>Loan</th><th>Type</th><th>Status</th><th>Required</th><th>Commission</th></tr></thead><tbody>{(data.loans||[]).map((l:any)=><tr key={l._id}><td>{l.loanId}</td><td>{l.loanType}</td><td><span className="status">{l.status}</span></td><td>{money(l.requiredAmount)}</td><td>{money(l.commission||0)}</td></tr>)}{!data.loans?.length&&<tr><td colSpan={5} className="empty">No loans.</td></tr>}</tbody></table></HistorySection><HistorySection title="Cars Bought"><table><thead><tr><th>Sale</th><th>Vehicle</th><th>Sale Date</th><th>Amount</th><th>Profit</th></tr></thead><tbody>{(data.carsBought||[]).map((x:any)=><tr key={x._id}><td>{x.saleId}</td><td>{x.carId?.vehicleId} — {x.carId?.make} {x.carId?.model}</td><td>{x.saleDate?new Date(x.saleDate).toLocaleDateString("en-IN"):"—"}</td><td>{money(x.sellingPrice)}</td><td className={x.profit>=0?"profit-positive":"profit-negative"}>{money(x.profit)}</td></tr>)}{!data.carsBought?.length&&<tr><td colSpan={5} className="empty">No cars bought.</td></tr>}</tbody></table></HistorySection><HistorySection title="Cars Sold"><table><thead><tr><th>Vehicle</th><th>Registration</th><th>Year</th><th>Purchase Price</th><th>Status</th></tr></thead><tbody>{(data.carsSold||[]).map((x:any)=><tr key={x._id}><td>{x.vehicleId}</td><td>{x.registrationNumber}</td><td>{x.year}</td><td>{money(x.purchasePrice)}</td><td><span className="status">{x.status}</span></td></tr>)}{!data.carsSold?.length&&<tr><td colSpan={5} className="empty">No cars sold.</td></tr>}</tbody></table></HistorySection></>}</section></div>
}
function HistorySection({title,children}:{title:string;children:any}){return <div className="history-section"><h3>{title}</h3><div className="table-wrap">{children}</div></div>}

function LoansPage({filter}:{filter:string}){
 const[loans,setLoans]=useState<Loan[]>([]);const[selected,setSelected]=useState<Loan|null>(null);const[detail,setDetail]=useState<any>(null);const[message,setMessage]=useState("");const[error,setError]=useState("");
 const load=()=>api.get("/loans").then(r=>setLoans(r.data.data)).catch(()=>setError("Unable to load loans."));
 useEffect(()=>{setError("");setMessage("");if(filter!=="Loan Revenue"&&filter!=="Follow-ups")load()},[filter]);
 async function openLoan(l:Loan){setSelected(l);setError("");try{const r=await api.get("/loans/"+l._id);setDetail(r.data.data)}catch(e:any){setError(e?.response?.data?.message||"Unable to load loan details.")}}
 async function status(id:string,next:string){setError("");try{const r=await api.patch("/loans/"+id+"/status",{status:next});setMessage("Loan status updated.");load();if(selected?._id===id){setSelected(r.data.data);openLoan(r.data.data)}}catch(e:any){setError(e?.response?.data?.message||"Unable to update status.")}}
 async function remove(l:Loan){if(!window.confirm("Delete this loan and its follow-ups permanently?"))return;setError("");try{await api.delete("/loans/"+l._id);setMessage("Loan deleted successfully.");load();if(selected?._id===l._id)setSelected(null)}catch(e:any){setError(e?.response?.data?.message||"Unable to delete loan.")}}
 if(filter==="Loan Revenue")return <LoanRevenuePage/>;if(filter==="Follow-ups")return <FollowUpsPage onOpen={openLoan} message={message} error={error}/>;
 const visible=filter==="Active Loans"?loans.filter(l=>["APPROVED","DISBURSED","CLOSED"].includes(l.status)):loans;
 return <>{error&&<div className="error-box">{error}</div>}<section className="panel"><div className="panel-head"><div><p>{filter==="Loan Dashboard"?"Pipeline overview and recent finance activity.":filter==="Active Loans"?"Approved, disbursed and closed loans.":"Manage finance applications."}</p></div>{filter!=="Active Loans"&&filter!=="Loan Dashboard"&&<button className="primary-btn" onClick={()=>navigateTo("New Loan")}>New Loan</button>}</div>{filter==="Loan Dashboard"?<LoanPipeline loans={loans}/>:<div className="table-wrap"><table><thead><tr><th>ID</th><th>Customer</th><th>Type</th><th>Required</th><th>Finance</th><th>Status</th><th>Action</th></tr></thead><tbody>{visible.map(l=><tr key={l._id}><td>{l.loanId}</td><td>{l.customerId?.name}</td><td>{l.loanType}</td><td>{money(l.requiredAmount)}</td><td>{l.financeCompany||"—"}</td><td><span className="status">{l.status}</span></td><td><div className="action-buttons"><button className="small-btn" onClick={()=>openLoan(l)}>View</button><button className="small-btn delete-btn" onClick={()=>remove(l)}>Delete</button></div></td></tr>)}{!visible.length&&<tr><td colSpan={7} className="empty">No loans found.</td></tr>}</tbody></table></div>}</section>{selected&&<LoanDetail loan={selected} detail={detail} onClose={()=>setSelected(null)} onStatus={status} follow={{followUpDate:"",nextFollowUpDate:"",note:""}} setFollow={()=>{}} addFollowUp={()=>{}}/>}</>
}
function LoanPipeline({loans}:{loans:Loan[]}){const stages=["ENTERED","DOCUMENTS_PENDING","SUBMITTED","UNDER_REVIEW","APPROVED","DISBURSED","CLOSED"];return <div className="pipeline">{stages.map(s=><div className="pipeline-item" key={s}><span>{s.replaceAll("_"," ")}</span><strong>{loans.filter(l=>l.status===s).length}</strong></div>)}</div>}
function LoanDetail({loan,detail,onClose,onStatus,follow,setFollow,addFollowUp}:{loan:Loan;detail:any;onClose:()=>void;onStatus:(id:string,status:string)=>void;follow:any;setFollow:(x:any)=>void;addFollowUp:(e:FormEvent)=>void}){const followUps=detail?.followUps||[];return <div className="modal-backdrop"><section className="modal-panel"><div className="panel-head"><div><h2>{loan.loanId} · {loan.customerId?.name}</h2><p>{loan.loanType} · {loan.financeCompany||"Finance company not set"}</p></div><button className="small-btn" onClick={onClose}>Close</button></div><div className="detail-grid"><div><b>Required</b><span>{money(loan.requiredAmount)}</span></div><div><b>Approved</b><span>{money(loan.approvedAmount||0)}</span></div><div><b>Commission</b><span>{money(loan.commission||0)}</span></div><div><b>Status</b><span className="status">{loan.status}</span></div></div><div className="status-actions"><b>Update status</b>{["DOCUMENTS_PENDING","SUBMITTED","UNDER_REVIEW","APPROVED","REJECTED","DISBURSED","CLOSED"].map(s=><button key={s} className="small-btn" onClick={()=>onStatus(loan._id,s)}>{s.replaceAll("_"," ")}</button>)}</div><div className="modal-section"><h3>Follow-ups</h3>{followUps.map((x:any)=><div className="follow-row" key={x._id}><span>{new Date(x.followUpDate).toLocaleDateString("en-IN")}</span><span>{x.note}</span><span className="status">{x.status}</span></div>)}{!followUps.length&&<p>No follow-ups yet.</p>}<form className="form-grid" onSubmit={addFollowUp}><input type="date" value={follow.followUpDate} onChange={e=>setFollow({...follow,followUpDate:e.target.value})} required/><input type="date" value={follow.nextFollowUpDate} onChange={e=>setFollow({...follow,nextFollowUpDate:e.target.value})}/><input className="full" placeholder="Follow-up note" value={follow.note} onChange={e=>setFollow({...follow,note:e.target.value})} required/><button className="primary-btn full">Add Follow-up</button></form></div></section></div>}
function FollowUpsPage({onOpen,message,error}:{onOpen:(l:Loan)=>void;message:string;error:string}){const[data,setData]=useState<any[]>([]);const[summary,setSummary]=useState<any>({open:0,overdue:0,dueToday:0,upcoming:0});const[busy,setBusy]=useState("");const[nextId,setNextId]=useState("");const[nextDate,setNextDate]=useState("");const[nextNote,setNextNote]=useState("");const load=()=>api.get("/loans/follow-ups",{params:{status:"OPEN"}}).then(r=>{setData(r.data.data);setSummary(r.data.summary||{})}).catch(()=>{});useEffect(()=>{load()},[]);
 async function removeFollowUp(x:any){if(!window.confirm("Delete this follow-up permanently?"))return;try{await api.delete("/loans/"+x.loanId?._id+"/follow-ups/"+x._id);load()}catch(e:any){alert(e?.response?.data?.message||"Unable to delete follow-up.")}}
 async function complete(x:any){setBusy(x._id);try{const body:any={status:"COMPLETED"};if(nextId===x._id){if(nextDate){body.nextFollowUpDate=new Date(nextDate).toISOString();body.nextNote=nextNote}else if(nextNote){throw new Error("Enter a next follow-up date.")}}await api.patch("/loans/"+x.loanId?._id+"/follow-ups/"+x._id,body);setNextId("");setNextDate("");setNextNote("");load()}catch(e:any){alert(e?.response?.data?.message||e.message||"Unable to complete follow-up.")}finally{setBusy("")}}
 const bucket=(x:any)=>{const d=new Date(x.followUpDate),n=new Date();const day=new Date(n.getFullYear(),n.getMonth(),n.getDate());if(d<day)return"OVERDUE";if(d<new Date(day.getFullYear(),day.getMonth(),day.getDate()+1))return"DUE TODAY";return"UPCOMING"};
 return <section className="panel"><div className="panel-head"><div><p>Complete a follow-up and optionally schedule the next customer touchpoint.</p></div></div>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<div className="cards compact"><Card label="Open" value={String(summary.open||0)}/><Card label="Overdue" value={String(summary.overdue||0)}/><Card label="Due Today" value={String(summary.dueToday||0)}/><Card label="Next 7 Days" value={String(summary.upcoming||0)}/></div><div className="table-wrap"><table><thead><tr><th>Priority</th><th>Date</th><th>Loan</th><th>Customer</th><th>Note</th><th>Action</th></tr></thead><tbody>{data.map(x=><tr key={x._id}><td><span className={"status "+bucket(x).toLowerCase().replace(" ","-")}>{bucket(x)}</span></td><td>{new Date(x.followUpDate).toLocaleDateString("en-IN")}</td><td>{x.loanId?.loanId}</td><td>{x.loanId?.customerId?.name||"—"}</td><td><div>{x.note}</div>{nextId===x._id&&<div className="follow-next"><input type="date" value={nextDate} onChange={e=>setNextDate(e.target.value)} placeholder="Next date"/><input value={nextNote} onChange={e=>setNextNote(e.target.value)} placeholder="Next follow-up note"/></div>}</td><td><div className="action-buttons"><button className="small-btn" onClick={()=>onOpen(x.loanId)}>View</button><button className="small-btn delete-btn" onClick={()=>removeFollowUp(x)}>Delete</button>{nextId!==x._id?<><button className="small-btn" onClick={()=>setNextId(x._id)}>Schedule Next</button><button className="small-btn" disabled={busy===x._id} onClick={()=>complete(x)}>{busy===x._id?"Saving...":"Complete"}</button></>:<button className="small-btn" disabled={busy===x._id} onClick={()=>complete(x)}>{busy===x._id?"Saving...":"Complete & Schedule"}</button>}</div></td></tr>)}{!data.length&&<tr><td colSpan={6} className="empty">No open follow-ups.</td></tr>}</tbody></table></div></section>}
function LoanRevenuePage(){const[data,setData]=useState<any>(null);useEffect(()=>{api.get("/reports/loan-revenue").then(r=>setData(r.data.data)).catch(()=>{})},[]);const s=data?.summary;return <section className="panel"><div className="panel-head"><div><p>Commission earned from approved and disbursed finance business.</p></div></div><div className="cards compact"><Card label="Approved+ Commission" value={money(s?.totalCommission??0)}/><Card label="Disbursed Commission" value={money(s?.disbursedCommission??0)}/><Card label="Qualified Loans" value={String(s?.approvedOrBetter??0)}/></div><div className="module-grid revenue-grid"><div><h3>By Loan Type</h3>{Object.entries(data?.byType||{}).map(([k,v]:any)=><div className="metric-row" key={k}><span>{k}</span><strong>{money(v)}</strong></div>)}</div><div><h3>By Finance Company</h3>{Object.entries(data?.byFinance||{}).map(([k,v]:any)=><div className="metric-row" key={k}><span>{k}</span><strong>{money(v)}</strong></div>)}</div></div><div className="table-wrap"><table><thead><tr><th>Loan</th><th>Customer</th><th>Type</th><th>Status</th><th>Commission</th></tr></thead><tbody>{(data?.loans||[]).map((l:Loan)=><tr key={l._id}><td>{l.loanId}</td><td>{l.customerId?.name}</td><td>{l.loanType}</td><td><span className="status">{l.status}</span></td><td>{money(l.commission||0)}</td></tr>)}</tbody></table></div></section>}

function CarBuyingPage(){
 const[customers,setCustomers]=useState<Customer[]>([]);const[form,setForm]=useState({sellerId:"",registrationNumber:"",make:"",model:"",year:"",ownerNumber:"1",km:"",fuel:"Petrol",purchasePrice:""});const[message,setMessage]=useState("");
 useEffect(()=>{api.get("/customers").then(r=>setCustomers(r.data.data))},[]);
 async function add(e:FormEvent){e.preventDefault();try{await api.post("/cars",{...form,year:Number(form.year),ownerNumber:Number(form.ownerNumber),km:Number(form.km),purchasePrice:Number(form.purchasePrice)});setMessage("Car purchase recorded and added to inventory.");}catch(e:any){setMessage(e?.response?.data?.message||"Unable to record car purchase.")}}
 return <section className="panel narrow"><p>Record a vehicle purchase. Expenses and final profit are linked automatically.</p><form className="form-grid" onSubmit={add}><PremiumSelect value={form.sellerId} onChange={value=>setForm({...form,sellerId:value})} placeholder="Select seller" options={customers.map(c=>({value:c._id,label:`undefined — undefined`}))}/><input placeholder="Registration number" value={form.registrationNumber} onChange={e=>setForm({...form,registrationNumber:e.target.value})} required/><input placeholder="Make" value={form.make} onChange={e=>setForm({...form,make:e.target.value})} required/><input placeholder="Model" value={form.model} onChange={e=>setForm({...form,model:e.target.value})} required/><input type="number" placeholder="Year" value={form.year} onChange={e=>setForm({...form,year:e.target.value})} required/><input type="number" placeholder="Owner number" value={form.ownerNumber} onChange={e=>setForm({...form,ownerNumber:e.target.value})}/><input type="number" placeholder="KM" value={form.km} onChange={e=>setForm({...form,km:e.target.value})} required/><PremiumSelect value={form.fuel} onChange={value=>setForm({...form,fuel:value})} placeholder="Select fuel type" options={["Petrol","Diesel","CNG","Electric","Hybrid"].map(x=>({value:x,label:x}))}/><input type="number" placeholder="Purchase price" value={form.purchasePrice} onChange={e=>setForm({...form,purchasePrice:e.target.value})} required/>{message&&<div className="success-box full">{message}</div>}<button className="primary-btn full">Record Purchase</button></form></section>
}

function CarsPage({mode,userRole}:{mode:string;userRole:"ADMIN"|"STAFF"}){
 const[cars,setCars]=useState<Car[]>([]);const[selected,setSelected]=useState<any>(null);const[message,setMessage]=useState("");const[error,setError]=useState("");
 const load=()=>api.get("/cars",{params:{status:mode==="Car Inventory"?"AVAILABLE":undefined}}).then(r=>setCars(r.data.data)).catch(()=>setError("Unable to load cars."));
 useEffect(()=>{load()},[mode]);
 async function changeStatus(car:Car,status:string){setMessage("");setError("");try{const r=await api.patch("/cars/"+car._id+"/status",{status});setCars(prev=>prev.map(x=>x._id===car._id?{...x,...r.data.data}:x));setMessage(car.vehicleId+" status updated to "+status+".")}catch(e:any){setError(e?.response?.data?.message||"Unable to update vehicle status.")}}
 async function remove(car:Car){if(!window.confirm("Delete this vehicle permanently?"))return;setMessage("");setError("");try{await api.delete("/cars/"+car._id);setMessage("Vehicle deleted successfully.");load();if(selected?.car?._id===car._id)setSelected(null)}catch(e:any){setError(e?.response?.data?.message||"Unable to delete vehicle.")}}
 async function view(car:Car){setError("");setSelected({loading:true,car});try{const r=await api.get("/cars/"+car._id+"/financials");setSelected({loading:false,car:r.data.data.car,details:r.data.data})}catch(e:any){setError(e?.response?.data?.message||"Unable to load vehicle details.");setSelected(null)}}
 return <section className="panel"><div className="panel-head"><div><p>Vehicle purchase price plus every expense is treated as the current investment for profit calculation.</p></div></div>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Registration</th><th>Model</th><th>Purchase Price</th><th>Expenses</th><th>Total Investment</th><th>Status</th><th>Action</th></tr></thead><tbody>{cars.map(c=><tr key={c._id}><td>{c.vehicleId}</td><td>{c.registrationNumber}</td><td>{c.make} {c.model} ({c.year})</td><td>{money(c.purchasePrice)}</td><td>{money(c.expenseTotal||0)}</td><td><strong>{money(c.totalInvestment??c.purchasePrice)}</strong></td><td>{userRole==="ADMIN"?<PremiumSelect value={c.status} onChange={status=>changeStatus(c,status)} placeholder="Select status" options={[{value:"AVAILABLE",label:"AVAILABLE"},{value:"RESERVED",label:"RESERVED"},{value:"SOLD",label:"SOLD"}]}/>:<span className="status">{c.status}</span>}</td><td><div className="action-buttons"><button className="small-btn" onClick={()=>view(c)}>View</button><button className="small-btn delete-btn" onClick={()=>remove(c)}>Delete</button></div></td></tr>)}{!cars.length&&<tr><td colSpan={8} className="empty">No vehicles found.</td></tr>}</tbody></table></div></section>{selected&&<CarFinancialModal state={selected} onClose={()=>setSelected(null)}/>}
}
function ExpensesPage(){
 const[expenses,setExpenses]=useState<CarExpense[]>([]);const[selected,setSelected]=useState<CarExpense|null>(null);const[message,setMessage]=useState("");const[error,setError]=useState("");
 const load=()=>api.get("/cars/expenses").then(r=>setExpenses(r.data.data)).catch(e=>setError(e?.response?.data?.message||"Unable to load expenses."));useEffect(()=>{load()},[]);
 async function remove(x:CarExpense){if(!window.confirm("Delete this expense permanently?"))return;setMessage("");setError("");try{await api.delete("/cars/"+x.carId?._id+"/expenses/"+x._id);setMessage("Expense deleted successfully.");load();if(selected?._id===x._id)setSelected(null)}catch(e:any){setError(e?.response?.data?.message||"Unable to delete expense.")}}
 return <section className="panel"><div className="panel-head"><div><h2>Vehicle Expenses</h2><p>Review every expense linked to inventory vehicles.</p></div><button className="primary-btn" onClick={()=>navigateTo("Add Expense")}>Add Expense</button></div>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Category</th><th>Description</th><th>Date</th><th>Amount</th><th>Action</th></tr></thead><tbody>{expenses.map(x=><tr key={x._id}><td>{x.carId?.vehicleId||"—"}<br/><small>{x.carId?.registrationNumber||""}</small></td><td>{x.category}</td><td>{x.description||"—"}</td><td>{x.date?new Date(x.date).toLocaleDateString("en-IN"):"—"}</td><td>{money(x.amount)}</td><td><div className="action-buttons"><button className="small-btn" onClick={()=>setSelected(x)}>View</button><button className="small-btn delete-btn" onClick={()=>remove(x)}>Delete</button><button className="small-btn" onClick={()=>navigateTo("Edit Expense",{expenseId:x._id})}>Edit</button></div></td></tr>)}{!expenses.length&&<tr><td colSpan={6} className="empty">No expenses recorded yet.</td></tr>}</tbody></table></div></section>{selected&&<ExpenseViewModal expense={selected} onClose={()=>setSelected(null)}/>}
}
function ProfitPage(){
 const[data,setData]=useState<any>(null);useEffect(()=>{api.get("/cars/profits").then(r=>setData(r.data.data))},[]);
 const s=data?.summary;
 return <section className="panel"><div className="panel-head"><div><h2>Car Profit Report</h2><p>Separate profit for every sold vehicle.</p></div></div><div className="cards compact"><Card label="Total Sales" value={money(s?.sales??0)}/><Card label="Total Investment" value={money(s?.investment??0)}/><Card label="Selling Expenses" value={money(s?.sellingExpenses??0)}/><Card label="Net Profit" value={money(s?.profit??0)}/></div><div className="table-wrap"><table><thead><tr><th>Sale</th><th>Vehicle</th><th>Buyer</th><th>Investment</th><th>Sale Value</th><th>Profit</th></tr></thead><tbody>{(data?.sales??[]).map((x:any)=><tr key={x._id}><td>{x.saleId}</td><td>{x.carId?.vehicleId} — {x.carId?.make} {x.carId?.model}</td><td>{x.buyerId?.name||"—"}</td><td>{money(x.totalInvestment)}</td><td>{money(x.sellingPrice)}</td><td className={x.profit>=0?"profit-positive":"profit-negative"}>{money(x.profit)}</td></tr>)}{!(data?.sales?.length)&&<tr><td colSpan={6} className="empty">No sold cars yet.</td></tr>}</tbody></table></div></section>
}

function CarSoldPage(){
 const[cars,setCars]=useState<Car[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[carId,setCarId]=useState("");const[buyerId,setBuyerId]=useState("");const[price,setPrice]=useState("");const[expenses,setExpenses]=useState("0");const[message,setMessage]=useState("");
 useEffect(()=>{api.get("/cars",{params:{status:"AVAILABLE"}}).then(r=>setCars(r.data.data));api.get("/customers").then(r=>setCustomers(r.data.data))},[]);
 async function sell(e:FormEvent){e.preventDefault();try{const r=await api.post(`/cars/${carId}/sell`,{buyerId,sellingPrice:Number(price),sellingExpenses:Number(expenses)});setMessage(`Sold successfully. Net profit: ${money(r.data.data.profit)}`);setCars(cars.filter(c=>c._id!==carId));}catch(e:any){setMessage(e?.response?.data?.message||"Unable to complete sale.")}}
 return <section className="panel narrow"><p>Sell an inventory vehicle and calculate net profit automatically.</p><form onSubmit={sell}><PremiumSelect value={carId} onChange={setCarId} placeholder="Select vehicle" options={cars.map(c=>({value:c._id,label:`undefined — undefined — undefined undefined`}))}/><PremiumSelect value={buyerId} onChange={setBuyerId} placeholder="Select buyer" options={customers.map(c=>({value:c._id,label:`undefined — undefined`}))}/><input type="number" placeholder="Selling price" value={price} onChange={e=>setPrice(e.target.value)} required/><input type="number" placeholder="Selling expenses" value={expenses} onChange={e=>setExpenses(e.target.value)}/>{message&&<div className="success-box">{message}</div>}<button className="primary-btn">Complete Sale</button></form></section>
}