import { FormEvent, useEffect, useState } from "react";
import { api } from "./services/api";

type User={id:string;name:string;email:string;role:"ADMIN"|"STAFF";isActive?:boolean};
type Customer={_id:string;customerId:string;name:string;mobile:string;email?:string;city?:string;occupation?:string};
type Loan={_id:string;loanId:string;customerId:Customer;loanType:string;requiredAmount:number;approvedAmount?:number;financeCompany?:string;status:string;commission:number;applicationDate?:string;expectedDisbursementDate?:string;disbursementDate?:string;rejectionReason?:string;notes?:string};
type Car={_id:string;vehicleId:string;registrationNumber:string;make:string;model:string;year:number;ownerNumber:number;km:number;fuel:string;purchasePrice:number;status:string;sellerId?:Customer};
type Dashboard={customers:number;activeLoans:number;carsInInventory:number;carsSold:number;totalSales:number;totalInvestment:number;totalProfit:number};

const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v);
const nav=[["Dashboard","Dashboard"],["Loan Dashboard","Loans"],["Applications","Loans"],["Active Loans","Loans"],["Car Buying","Car Buying"],["Car Inventory","Cars"],["Car Sold","Sold"],["Expenses","Cars"],["Customers","Customers"],["Customer History","Customers"],["Car Profit","Profit"],["Loan Revenue","Loans"],["Reports","Dashboard"]];

export default function App(){
 const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{api.get("/auth/me").then(r=>setUser(r.data.data)).catch(()=>localStorage.removeItem("sm_token")).finally(()=>setLoading(false))},[]);
 if(loading)return <div className="center-page"><div className="loader-card">Loading SM Associate...</div></div>;
 if(!user)return <Login onLogin={setUser}/>;
 return <ManagementApp user={user} onLogout={()=>{localStorage.removeItem("sm_token");setUser(null)}}/>;
}

function Login({onLogin}:{onLogin:(u:User)=>void}){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const r=await api.post("/auth/login",{email,password});localStorage.setItem("sm_token",r.data.data.token);onLogin(r.data.data.user)}catch(e:any){setError(e?.response?.data?.message||"Unable to sign in. Please try again.")}finally{setBusy(false)}}
 return <div className="login-page"><div className="login-panel"><div className="login-brand">SM ASSOCIATE</div><h1>Management System</h1><p>Secure access for finance and car operations.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error-box">{error}</div>}<button className="primary-btn" disabled={busy}>{busy?"Signing in...":"Sign in"}</button></form></div></div>
}

function ManagementApp({user,onLogout}:{user:User;onLogout:()=>void}){
 const[page,setPage]=useState("Dashboard");
 return <div className="app"><aside className="sidebar"><div className="brand">SM ASSOCIATE</div><nav>
 <div className="nav-title">GENERAL</div><Nav label="Dashboard" page={page} setPage={setPage}/>
 <div className="nav-title">LOAN MANAGEMENT</div>{["Loan Dashboard","Applications","Active Loans","Follow-ups"].map(x=><Nav key={x} label={x} page={page} setPage={setPage}/>)}
 <div className="nav-title">CAR MANAGEMENT</div>{(user.role==="ADMIN"?["Car Buying","Car Inventory","Car Sold","Expenses"]:["Car Buying","Car Inventory","Expenses"]).map(x=><Nav key={x} label={x} page={page} setPage={setPage}/>)}
 <div className="nav-title">CUSTOMER MANAGEMENT</div>{["Customers","Customer History"].map(x=><Nav key={x} label={x} page={page} setPage={setPage}/>)}
 <div className="nav-title">PROFIT & REPORTS</div>{user.role==="ADMIN"?["Car Profit","Loan Revenue","Reports"].map(x=><Nav key={x} label={x} page={page} setPage={setPage}/>):<Nav label="Reports" page={page} setPage={setPage}/>}
 {user.role==="ADMIN"&&<><div className="nav-title">ADMINISTRATION</div><Nav label="Users" page={page} setPage={setPage}/></>}</nav>
 <div className="sidebar-user"><strong>{user.name}</strong><span>{user.role}</span><button onClick={onLogout}>Sign out</button></div></aside>
 <main className="main"><header><div><h1>{page}</h1><p>SM Associate Management System</p></div><div className="user-pill">{user.name}</div></header><PageContent page={page}/></main></div>
}
function Nav({label,page,setPage}:{label:string;page:string;setPage:(x:string)=>void}){return <button className={page===label?"nav-link active":"nav-link"} onClick={()=>setPage(label)}>{label}</button>}

function PageContent({page}:{page:string}){
 if(page==="Users")return <UsersPage/>;
 if(page==="Customers"||page==="Customer History")return <CustomersPage historyOnly={page==="Customer History"}/>;
 if(page==="Loans"||page==="Loan Dashboard"||page==="Applications"||page==="Active Loans"||page==="Follow-ups"||page==="Loan Revenue")return <LoansPage filter={page}/>;
 if(page==="Cars"||page==="Car Inventory"||page==="Expenses")return <CarsPage mode={page}/>;
 if(page==="Car Profit")return <ProfitPage/>;
 if(page==="Car Buying")return <CarBuyingPage/>;
 if(page==="Car Sold")return <CarSoldPage/>;
 return <DashboardPage/>;
}

function UsersPage(){
 const[users,setUsers]=useState<User[]>([]);const[form,setForm]=useState({name:"",email:"",password:"",role:"STAFF"});const[message,setMessage]=useState("");const[error,setError]=useState("");
 const load=()=>api.get("/auth/users").then(r=>setUsers(r.data.data)).catch(e=>setError(e?.response?.data?.message||"Unable to load users."));
 useEffect(()=>{load()},[]);
 async function add(e:FormEvent){e.preventDefault();setMessage("");setError("");try{await api.post("/auth/users",form);setForm({name:"",email:"",password:"",role:"STAFF"});setMessage("User created successfully.");load()}catch(e:any){setError(e?.response?.data?.message||"Unable to create user.")}}
 async function toggle(u:User){setMessage("");setError("");try{await api.patch("/auth/users/"+u.id,{isActive:!u.isActive});setMessage("User access updated.");load()}catch(e:any){setError(e?.response?.data?.message||"Unable to update user.")}}
 async function changeRole(u:User,role:"ADMIN"|"STAFF"){setMessage("");setError("");try{await api.patch("/auth/users/"+u.id,{role});setMessage("Role updated.");load()}catch(e:any){setError(e?.response?.data?.message||"Unable to update role.")}}
 return <div className="module-grid"><section className="panel"><div className="panel-head"><div><h2>User Management</h2><p>ADMIN-only access. Control staff accounts and roles.</p></div></div>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td><select value={u.role} onChange={e=>changeRole(u,e.target.value as "ADMIN"|"STAFF")}><option value="STAFF">STAFF</option><option value="ADMIN">ADMIN</option></select></td><td><span className="status">{u.isActive?"ACTIVE":"INACTIVE"}</span></td><td><button className="small-btn" onClick={()=>toggle(u)}>{u.isActive?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div></section><section className="panel form-panel"><h2>Create User</h2><form onSubmit={add}><input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Password (min 8 characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength={8} required/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="STAFF">STAFF</option><option value="ADMIN">ADMIN</option></select><button className="primary-btn">Create User</button></form></section></div>
}

function DashboardPage(){
 const[data,setData]=useState<Dashboard|null>(null);const[error,setError]=useState("");
 useEffect(()=>{api.get("/reports/dashboard").then(r=>setData(r.data.data)).catch(e=>setError(e?.response?.data?.message||"Unable to load dashboard."))},[]);
 return <>{error&&<div className="error-box">{error}</div>}<section className="cards"><Card label="Total Customers" value={String(data?.customers??0)}/><Card label="Active Loans" value={String(data?.activeLoans??0)}/><Card label="Cars in Inventory" value={String(data?.carsInInventory??0)}/><Card label="Cars Sold" value={String(data?.carsSold??0)}/></section><section className="profit-card"><div><span>Total Investment</span><strong>{money(data?.totalInvestment??0)}</strong></div><div><span>Total Sales</span><strong>{money(data?.totalSales??0)}</strong></div><div><span>Net Car Profit</span><strong>{money(data?.totalProfit??0)}</strong></div></section></>;
}
function Card({label,value}:{label:string;value:string}){return <div className="card"><span>{label}</span><strong>{value}</strong></div>}

function CustomersPage({historyOnly}:{historyOnly:boolean}){
 const[customers,setCustomers]=useState<Customer[]>([]);const[search,setSearch]=useState("");const[selected,setSelected]=useState<Customer|null>(null);const[history,setHistory]=useState<any>(null);const[form,setForm]=useState({name:"",mobile:"",email:"",city:"",occupation:""});const[message,setMessage]=useState("");
 const load=()=>api.get("/customers",{params:{search}}).then(r=>setCustomers(r.data.data)).catch(()=>setMessage("Unable to load customers."));
 useEffect(()=>{load()},[search]);
 async function add(e:FormEvent){e.preventDefault();setMessage("");try{await api.post("/customers",form);setForm({name:"",mobile:"",email:"",city:"",occupation:""});setMessage("Customer added successfully.");load()}catch(e:any){setMessage(e?.response?.data?.message||"Unable to save customer.")}}
 async function open(c:Customer){setSelected(c);try{const r=await api.get("/customers/"+c._id+"/history");setHistory(r.data.data)}catch(e:any){setMessage(e?.response?.data?.message||"Unable to load customer history.")}}
 return <><div className="module-grid"><section className="panel"><div className="panel-head"><div><h2>{historyOnly?"Customer History":"Customers"}</h2><p>{historyOnly?"Select a customer to view their complete transaction history.":"Manage customer records and linked transactions."}</p></div></div><input className="search" placeholder="Search name, mobile or customer ID..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Mobile</th><th>City</th><th>Occupation</th><th>Action</th></tr></thead><tbody>{customers.map(c=><tr key={c._id}><td>{c.customerId}</td><td>{c.name}</td><td>{c.mobile}</td><td>{c.city||"—"}</td><td>{c.occupation||"—"}</td><td><button className="small-btn" onClick={()=>open(c)}>{historyOnly?"View History":"History"}</button></td></tr>)}{!customers.length&&<tr><td colSpan={6} className="empty">No customers found.</td></tr>}</tbody></table></div></section>{!historyOnly&&<section className="panel form-panel"><h2>Add Customer</h2><form onSubmit={add}>{["name","mobile","email","city","occupation"].map(k=><input key={k} placeholder={k[0].toUpperCase()+k.slice(1)} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==="name"||k==="mobile"}/>)}{message&&<div className="success-box">{message}</div>}<button className="primary-btn">Save Customer</button></form></section>}</div>{selected&&<CustomerHistoryModal customer={selected} data={history} onClose={()=>{setSelected(null);setHistory(null)}}/>}</>
}

function CustomerHistoryModal({customer,data,onClose}:{customer:Customer;data:any;onClose:()=>void}){
 const s=data?.summary;
 return <div className="modal-backdrop"><section className="modal-panel customer-history-modal"><div className="panel-head"><div><h2>{customer.customerId} · {customer.name}</h2><p>{customer.mobile}{customer.city?" · "+customer.city:""}{customer.occupation?" · "+customer.occupation:""}</p></div><button className="small-btn" onClick={onClose}>Close</button></div>{!data?<div className="loader-card">Loading customer history...</div>:<><div className="cards compact"><Card label="Loans" value={String(s?.loanCount??0)}/><Card label="Approved Amount" value={money(s?.loanApprovedAmount??0)}/><Card label="Loan Commission" value={money(s?.loanCommission??0)}/><Card label="Cars Bought" value={String(s?.carsBoughtCount??0)}/><Card label="Cars Sold" value={String(s?.carsSoldCount??0)}/><Card label="Cars Bought Value" value={money(s?.carsBoughtValue??0)}/></div><HistorySection title="Loans"><table><thead><tr><th>Loan</th><th>Type</th><th>Status</th><th>Required</th><th>Commission</th></tr></thead><tbody>{(data.loans||[]).map((l:any)=><tr key={l._id}><td>{l.loanId}</td><td>{l.loanType}</td><td><span className="status">{l.status}</span></td><td>{money(l.requiredAmount)}</td><td>{money(l.commission||0)}</td></tr>)}{!data.loans?.length&&<tr><td colSpan={5} className="empty">No loans.</td></tr>}</tbody></table></HistorySection><HistorySection title="Cars Bought"><table><thead><tr><th>Sale</th><th>Vehicle</th><th>Sale Date</th><th>Amount</th><th>Profit</th></tr></thead><tbody>{(data.carsBought||[]).map((x:any)=><tr key={x._id}><td>{x.saleId}</td><td>{x.carId?.vehicleId} — {x.carId?.make} {x.carId?.model}</td><td>{x.saleDate?new Date(x.saleDate).toLocaleDateString("en-IN"):"—"}</td><td>{money(x.sellingPrice)}</td><td className={x.profit>=0?"profit-positive":"profit-negative"}>{money(x.profit)}</td></tr>)}{!data.carsBought?.length&&<tr><td colSpan={5} className="empty">No cars bought.</td></tr>}</tbody></table></HistorySection><HistorySection title="Cars Sold"><table><thead><tr><th>Vehicle</th><th>Registration</th><th>Year</th><th>Purchase Price</th><th>Status</th></tr></thead><tbody>{(data.carsSold||[]).map((x:any)=><tr key={x._id}><td>{x.vehicleId}</td><td>{x.registrationNumber}</td><td>{x.year}</td><td>{money(x.purchasePrice)}</td><td><span className="status">{x.status}</span></td></tr>)}{!data.carsSold?.length&&<tr><td colSpan={5} className="empty">No cars sold.</td></tr>}</tbody></table></HistorySection></>}</section></div>
}
function HistorySection({title,children}:{title:string;children:any}){return <div className="history-section"><h3>{title}</h3><div className="table-wrap">{children}</div></div>}

function LoansPage({filter}:{filter:string}){
 const[loans,setLoans]=useState<Loan[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[selected,setSelected]=useState<Loan|null>(null);const[detail,setDetail]=useState<any>(null);
 const[form,setForm]=useState({customerId:"",loanType:"Home Loan",requiredAmount:"",financeCompany:"",commission:"",notes:""});const[follow,setFollow]=useState({followUpDate:"",nextFollowUpDate:"",note:""});const[message,setMessage]=useState("");const[error,setError]=useState("");
 const load=()=>api.get("/loans").then(r=>setLoans(r.data.data)).catch(()=>setError("Unable to load loans."));
 useEffect(()=>{setError("");setMessage("");if(filter!=="Loan Revenue"&&filter!=="Follow-ups")load();api.get("/customers").then(r=>setCustomers(r.data.data)).catch(()=>{})},[filter]);
 async function add(e:FormEvent){e.preventDefault();setMessage("");setError("");try{await api.post("/loans",{...form,requiredAmount:Number(form.requiredAmount),commission:Number(form.commission||0)});setMessage("Loan application created successfully.");setForm({customerId:"",loanType:"Home Loan",requiredAmount:"",financeCompany:"",commission:"",notes:""});load()}catch(e:any){setError(e?.response?.data?.message||"Unable to create loan.")}}
 async function openLoan(l:Loan){setSelected(l);setError("");try{const r=await api.get("/loans/"+l._id);setDetail(r.data.data)}catch(e:any){setError(e?.response?.data?.message||"Unable to load loan details.")}}
 async function status(id:string,next:string){setError("");try{const r=await api.patch("/loans/"+id+"/status",{status:next});setMessage("Loan status updated.");load();if(selected?._id===id){setSelected(r.data.data);openLoan(r.data.data)}}catch(e:any){setError(e?.response?.data?.message||"Unable to update status.")}}
 async function addFollowUp(e:FormEvent){e.preventDefault();if(!selected)return;try{await api.post("/loans/"+selected._id+"/follow-ups",{followUpDate:follow.followUpDate,nextFollowUpDate:follow.nextFollowUpDate||undefined,note:follow.note});setFollow({followUpDate:"",nextFollowUpDate:"",note:""});setMessage("Follow-up added.");openLoan(selected)}catch(e:any){setError(e?.response?.data?.message||"Unable to add follow-up.")}}
 if(filter==="Loan Revenue")return <LoanRevenuePage/>;if(filter==="Follow-ups")return <FollowUpsPage onOpen={openLoan} message={message} error={error}/>;
 const visible=filter==="Active Loans"?loans.filter(l=>["APPROVED","DISBURSED","CLOSED"].includes(l.status)):loans;
 return <><div className="module-grid"><section className="panel"><div className="panel-head"><div><h2>{filter==="Loan Dashboard"?"Loan Dashboard":filter}</h2><p>{filter==="Loan Dashboard"?"Pipeline overview and recent finance activity.":filter==="Active Loans"?"Approved, disbursed and closed loans.":"Create and manage finance applications."}</p></div></div>{filter==="Loan Dashboard"?<LoanPipeline loans={loans}/>:<div className="table-wrap"><table><thead><tr><th>ID</th><th>Customer</th><th>Type</th><th>Required</th><th>Finance</th><th>Status</th><th>Action</th></tr></thead><tbody>{visible.map(l=><tr key={l._id}><td>{l.loanId}</td><td>{l.customerId?.name}</td><td>{l.loanType}</td><td>{money(l.requiredAmount)}</td><td>{l.financeCompany||"—"}</td><td><span className="status">{l.status}</span></td><td><button className="small-btn" onClick={()=>openLoan(l)}>View</button></td></tr>)}{!visible.length&&<tr><td colSpan={7} className="empty">No loans found.</td></tr>}</tbody></table></div>}</section>{filter!=="Active Loans"&&<section className="panel form-panel"><h2>New Loan</h2><form onSubmit={add}><select value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})} required><option value="">Select customer</option>{customers.map(c=><option key={c._id} value={c._id}>{c.customerId} — {c.name}</option>)}</select><select value={form.loanType} onChange={e=>setForm({...form,loanType:e.target.value})}>{["Home Loan","Car Loan","Business Loan","Personal Loan"].map(x=><option key={x}>{x}</option>)}</select><input type="number" placeholder="Required amount" value={form.requiredAmount} onChange={e=>setForm({...form,requiredAmount:e.target.value})} required/><input placeholder="Finance company" value={form.financeCompany} onChange={e=>setForm({...form,financeCompany:e.target.value})}/><input type="number" placeholder="Commission" value={form.commission} onChange={e=>setForm({...form,commission:e.target.value})}/><textarea placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<button className="primary-btn">Create Application</button></form></section>}</div>{selected&&<LoanDetail loan={selected} detail={detail} onClose={()=>setSelected(null)} onStatus={status} follow={follow} setFollow={setFollow} addFollowUp={addFollowUp}/>}</>
}
function LoanPipeline({loans}:{loans:Loan[]}){const stages=["NEW","DOCUMENTS_PENDING","SUBMITTED","UNDER_REVIEW","APPROVED","DISBURSED","CLOSED"];return <div className="pipeline">{stages.map(s=><div className="pipeline-item" key={s}><span>{s.replaceAll("_"," ")}</span><strong>{loans.filter(l=>l.status===s).length}</strong></div>)}</div>}
function LoanDetail({loan,detail,onClose,onStatus,follow,setFollow,addFollowUp}:{loan:Loan;detail:any;onClose:()=>void;onStatus:(id:string,status:string)=>void;follow:any;setFollow:(x:any)=>void;addFollowUp:(e:FormEvent)=>void}){const followUps=detail?.followUps||[];return <div className="modal-backdrop"><section className="modal-panel"><div className="panel-head"><div><h2>{loan.loanId} · {loan.customerId?.name}</h2><p>{loan.loanType} · {loan.financeCompany||"Finance company not set"}</p></div><button className="small-btn" onClick={onClose}>Close</button></div><div className="detail-grid"><div><b>Required</b><span>{money(loan.requiredAmount)}</span></div><div><b>Approved</b><span>{money(loan.approvedAmount||0)}</span></div><div><b>Commission</b><span>{money(loan.commission||0)}</span></div><div><b>Status</b><span className="status">{loan.status}</span></div></div><div className="status-actions"><b>Update status</b>{["DOCUMENTS_PENDING","SUBMITTED","UNDER_REVIEW","APPROVED","REJECTED","DISBURSED","CLOSED"].map(s=><button key={s} className="small-btn" onClick={()=>onStatus(loan._id,s)}>{s.replaceAll("_"," ")}</button>)}</div><div className="modal-section"><h3>Follow-ups</h3>{followUps.map((x:any)=><div className="follow-row" key={x._id}><span>{new Date(x.followUpDate).toLocaleDateString("en-IN")}</span><span>{x.note}</span><span className="status">{x.status}</span></div>)}{!followUps.length&&<p>No follow-ups yet.</p>}<form className="form-grid" onSubmit={addFollowUp}><input type="date" value={follow.followUpDate} onChange={e=>setFollow({...follow,followUpDate:e.target.value})} required/><input type="date" value={follow.nextFollowUpDate} onChange={e=>setFollow({...follow,nextFollowUpDate:e.target.value})}/><input className="full" placeholder="Follow-up note" value={follow.note} onChange={e=>setFollow({...follow,note:e.target.value})} required/><button className="primary-btn full">Add Follow-up</button></form></div></section></div>}
function FollowUpsPage({onOpen,message,error}:{onOpen:(l:Loan)=>void;message:string;error:string}){const[data,setData]=useState<any[]>([]);const[busy,setBusy]=useState("");const load=()=>api.get("/loans/follow-ups",{params:{status:"OPEN"}}).then(r=>setData(r.data.data)).catch(()=>{});useEffect(()=>{load()},[]);async function complete(x:any){setBusy(x._id);try{await api.patch("/loans/"+x.loanId?._id+"/follow-ups/"+x._id,{status:"COMPLETED"});setData(data.filter(y=>y._id!==x._id))}finally{setBusy("")}}return <section className="panel"><div className="panel-head"><div><h2>Follow-ups</h2><p>Open follow-ups that need attention.</p></div></div>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Date</th><th>Loan</th><th>Customer</th><th>Note</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.map(x=><tr key={x._id}><td>{new Date(x.followUpDate).toLocaleDateString("en-IN")}</td><td>{x.loanId?.loanId}</td><td>{x.loanId?.customerId?.name||"—"}</td><td>{x.note}</td><td><span className="status">{x.status}</span></td><td><button className="small-btn" disabled={busy===x._id} onClick={()=>complete(x)}>{busy===x._id?"Saving...":"Complete"}</button></td></tr>)}{!data.length&&<tr><td colSpan={6} className="empty">No open follow-ups.</td></tr>}</tbody></table></div></section>}
function LoanRevenuePage(){const[data,setData]=useState<any>(null);useEffect(()=>{api.get("/reports/loan-revenue").then(r=>setData(r.data.data)).catch(()=>{})},[]);const s=data?.summary;return <section className="panel"><div className="panel-head"><div><h2>Loan Revenue</h2><p>Commission earned from approved and disbursed finance business.</p></div></div><div className="cards compact"><Card label="Approved+ Commission" value={money(s?.totalCommission??0)}/><Card label="Disbursed Commission" value={money(s?.disbursedCommission??0)}/><Card label="Qualified Loans" value={String(s?.approvedOrBetter??0)}/></div><div className="module-grid revenue-grid"><div><h3>By Loan Type</h3>{Object.entries(data?.byType||{}).map(([k,v]:any)=><div className="metric-row" key={k}><span>{k}</span><strong>{money(v)}</strong></div>)}</div><div><h3>By Finance Company</h3>{Object.entries(data?.byFinance||{}).map(([k,v]:any)=><div className="metric-row" key={k}><span>{k}</span><strong>{money(v)}</strong></div>)}</div></div><div className="table-wrap"><table><thead><tr><th>Loan</th><th>Customer</th><th>Type</th><th>Status</th><th>Commission</th></tr></thead><tbody>{(data?.loans||[]).map((l:Loan)=><tr key={l._id}><td>{l.loanId}</td><td>{l.customerId?.name}</td><td>{l.loanType}</td><td><span className="status">{l.status}</span></td><td>{money(l.commission||0)}</td></tr>)}</tbody></table></div></section>}

function CarBuyingPage(){
 const[customers,setCustomers]=useState<Customer[]>([]);const[form,setForm]=useState({sellerId:"",registrationNumber:"",make:"",model:"",year:"",ownerNumber:"1",km:"",fuel:"Petrol",purchasePrice:""});const[message,setMessage]=useState("");
 useEffect(()=>{api.get("/customers").then(r=>setCustomers(r.data.data))},[]);
 async function add(e:FormEvent){e.preventDefault();try{await api.post("/cars",{...form,year:Number(form.year),ownerNumber:Number(form.ownerNumber),km:Number(form.km),purchasePrice:Number(form.purchasePrice)});setMessage("Car purchase recorded and added to inventory.");}catch(e:any){setMessage(e?.response?.data?.message||"Unable to record car purchase.")}}
 return <section className="panel narrow"><h2>Car Buying</h2><p>Record a vehicle purchase. Expenses and final profit are linked automatically.</p><form className="form-grid" onSubmit={add}><select value={form.sellerId} onChange={e=>setForm({...form,sellerId:e.target.value})} required><option value="">Select seller</option>{customers.map(c=><option key={c._id} value={c._id}>{c.customerId} — {c.name}</option>)}</select><input placeholder="Registration number" value={form.registrationNumber} onChange={e=>setForm({...form,registrationNumber:e.target.value})} required/><input placeholder="Make" value={form.make} onChange={e=>setForm({...form,make:e.target.value})} required/><input placeholder="Model" value={form.model} onChange={e=>setForm({...form,model:e.target.value})} required/><input type="number" placeholder="Year" value={form.year} onChange={e=>setForm({...form,year:e.target.value})} required/><input type="number" placeholder="Owner number" value={form.ownerNumber} onChange={e=>setForm({...form,ownerNumber:e.target.value})}/><input type="number" placeholder="KM" value={form.km} onChange={e=>setForm({...form,km:e.target.value})} required/><select value={form.fuel} onChange={e=>setForm({...form,fuel:e.target.value})}>{["Petrol","Diesel","CNG","Electric","Hybrid"].map(x=><option key={x}>{x}</option>)}</select><input type="number" placeholder="Purchase price" value={form.purchasePrice} onChange={e=>setForm({...form,purchasePrice:e.target.value})} required/>{message&&<div className="success-box full">{message}</div>}<button className="primary-btn full">Record Purchase</button></form></section>
}

function CarsPage({mode}:{mode:string}){
 const[cars,setCars]=useState<Car[]>([]);const[message,setMessage]=useState("");
 const load=()=>api.get("/cars",{params:{status:mode==="Car Inventory"?"AVAILABLE":undefined}}).then(r=>setCars(r.data.data)).catch(()=>setMessage("Unable to load cars."));
 useEffect(()=>{load()},[mode]);
 async function addExpense(id:string){const amount=window.prompt("Expense amount");if(!amount)return;try{await api.post(`/cars/${id}/expenses`,{category:"General",amount:Number(amount),description:"Added from web"});setMessage("Expense added.");}catch(e:any){setMessage(e?.response?.data?.message||"Unable to add expense.")}}
 return <section className="panel"><div className="panel-head"><div><h2>{mode}</h2><p>Vehicles, investment and operating expenses.</p></div></div>{message&&<div className="success-box">{message}</div>}<div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Registration</th><th>Model</th><th>Purchase</th><th>Status</th>{mode==="Expenses"&&<th>Action</th>}</tr></thead><tbody>{cars.map(c=><tr key={c._id}><td>{c.vehicleId}</td><td>{c.registrationNumber}</td><td>{c.make} {c.model} ({c.year})</td><td>{money(c.purchasePrice)}</td><td><span className="status">{c.status}</span></td>{mode==="Expenses"&&<td><button className="small-btn" onClick={()=>addExpense(c._id)}>Add Expense</button></td>}</tr>)}{!cars.length&&<tr><td colSpan={6} className="empty">No vehicles found.</td></tr>}</tbody></table></div></section>
}

function ProfitPage(){
 const[data,setData]=useState<any>(null);useEffect(()=>{api.get("/cars/profits").then(r=>setData(r.data.data))},[]);
 const s=data?.summary;
 return <section className="panel"><div className="panel-head"><div><h2>Car Profit Report</h2><p>Separate profit for every sold vehicle.</p></div></div><div className="cards compact"><Card label="Total Sales" value={money(s?.sales??0)}/><Card label="Total Investment" value={money(s?.investment??0)}/><Card label="Selling Expenses" value={money(s?.sellingExpenses??0)}/><Card label="Net Profit" value={money(s?.profit??0)}/></div><div className="table-wrap"><table><thead><tr><th>Sale</th><th>Vehicle</th><th>Buyer</th><th>Investment</th><th>Sale Value</th><th>Profit</th></tr></thead><tbody>{(data?.sales??[]).map((x:any)=><tr key={x._id}><td>{x.saleId}</td><td>{x.carId?.vehicleId} — {x.carId?.make} {x.carId?.model}</td><td>{x.buyerId?.name||"—"}</td><td>{money(x.totalInvestment)}</td><td>{money(x.sellingPrice)}</td><td className={x.profit>=0?"profit-positive":"profit-negative"}>{money(x.profit)}</td></tr>)}{!(data?.sales?.length)&&<tr><td colSpan={6} className="empty">No sold cars yet.</td></tr>}</tbody></table></div></section>
}

function CarSoldPage(){
 const[cars,setCars]=useState<Car[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[carId,setCarId]=useState("");const[buyerId,setBuyerId]=useState("");const[price,setPrice]=useState("");const[expenses,setExpenses]=useState("0");const[message,setMessage]=useState("");
 useEffect(()=>{api.get("/cars",{params:{status:"AVAILABLE"}}).then(r=>setCars(r.data.data));api.get("/customers").then(r=>setCustomers(r.data.data))},[]);
 async function sell(e:FormEvent){e.preventDefault();try{const r=await api.post(`/cars/${carId}/sell`,{buyerId,sellingPrice:Number(price),sellingExpenses:Number(expenses)});setMessage(`Sold successfully. Net profit: ${money(r.data.data.profit)}`);setCars(cars.filter(c=>c._id!==carId));}catch(e:any){setMessage(e?.response?.data?.message||"Unable to complete sale.")}}
 return <section className="panel narrow"><h2>Car Sold</h2><p>Sell an inventory vehicle and calculate net profit automatically.</p><form onSubmit={sell}><select value={carId} onChange={e=>setCarId(e.target.value)} required><option value="">Select vehicle</option>{cars.map(c=><option key={c._id} value={c._id}>{c.vehicleId} — {c.registrationNumber} — {c.make} {c.model}</option>)}</select><select value={buyerId} onChange={e=>setBuyerId(e.target.value)} required><option value="">Select buyer</option>{customers.map(c=><option key={c._id} value={c._id}>{c.customerId} — {c.name}</option>)}</select><input type="number" placeholder="Selling price" value={price} onChange={e=>setPrice(e.target.value)} required/><input type="number" placeholder="Selling expenses" value={expenses} onChange={e=>setExpenses(e.target.value)}/>{message&&<div className="success-box">{message}</div>}<button className="primary-btn">Complete Sale</button></form></section>
}